- name: Install Ruby and Handler
  become: true
  hosts: all
  tasks:
    - name: apt update
      apt:
        update_cache: yes 
    - name: install ruby-full
      apt:
        name: ruby-full
        state: present 
    - name: install ruby-bundler
      apt: 
        name: ruby-bundler
        state: present 
    - name: install build-essential
      apt: 
        name: build-essential
        state: present 
